### ISSUE TITLE
veeam.sa credentials expire after few weeks

### ISSUE THREAD

**Issue by dlapointe-sherweb** [VeeamHub/veeam-plugin-for-vcd#10]
**Describe the bug**
The credentials of the SSO user veeam.sa automatically created by the plugin expires and vcloud user cannot access the managed backup plugin anymore. To resolve the issue, we need to go on the provider portal and access the plugin and click regenerate credentials everytime this happens.

**Expected behavior**
I would expected that the veeam.sa user credentials never expire.

**Comment by carceneaux** [comment]
I can confirm the credentials for `veeam.sa` are not set to expire.

If the credentials stop working after the fact, it's because something outside of the plugin changed them. Perhaps...

* A Tenant Org Admin changed the password for the `veeam.sa` account. If the password is changed outside of the plugin, this will break the SSO functionality.
* An account policy lockout is applied and someone is attempting to login to the `veeam.sa` account using incorrect credentials.

**Comment by carceneaux** [comment]
Closing due to no response.
