### ISSUE TITLE
Security implications of SSO feature

### ISSUE THREAD

**Issue by jaymzmac** [VeeamHub/veeam-plugin-for-vcd#7]
I'm not comfortable with the plugin creating a 'veeam.sa' account with organisation admin rights for all tenants. My concern has to do with security, and a lack of documentation regarding how this solution works:

1. How is the password for the veeam.sa account generated? 
2. How secure is this password? 
3. Where is this password stored for this account?
4. Is it unique for each tenant?
5. How does the veeam vcd plugin obtain the password in order to perform the login when the tenant opens the plugin?
6. Why is the account created for tenant organisations to whom we haven't even published the veeam plugin?

Rather than creating a 'veeam.sa' account, which in my opinion introduces a security risk, I would rather the plugin use the credentials of the user who is currently logged in to VMware Cloud Director. For example, this is how the VMware Cloud Director Availability plugin works.

Are there any implications if we manually disable / delete the 'veeam.sa' account for our tenants (apart from preventing SSO from working as intended)?

**Comment by carceneaux** [comment]
Hi @jaymzmac,

You have valid questions. Please see my responses inline below:

`How is the password for the veeam.sa account generated?`

It's generated using a random string generator.

`How secure is this password?`

Password length is 30 characters including at least 1 of each of the following:

* uppercase
* lowercase
* number
* symbol

`Where is this password stored for this account?`

It's encrypted and placed in VCD Organization metadata.

`Is it unique for each tenant?`

Yes

`How does the veeam vcd plugin obtain the password in order to perform the login when the tenant opens the plugin?`

Metadata is retrieved and password is used for login. Only users with Organization Administrator role are able to retrieve the metadata.

`Why is the account created for tenant organisations to whom we haven't even published the veeam plugin?`

This is the design of the plugin. If a tenant is not using the plugin, the account can be disabled/deleted.

`Are there any implications if we manually disable / delete the 'veeam.sa' account for our tenants (apart from preventing SSO from working as intended)?`

No. See previous answer.

`...I would rather the plugin use the credentials of the user who is currently logged in to VMware Cloud Director.`

You can use [v1.0 of the plugin](https://github.com/VeeamHub/veeam-plugin-for-vcd/releases/tag/v1.0) which doesn't have SSO enabled. This plugin works for VCD 10 as well.

Hope this answers your questions. If you have further questions, please let me know.

**Comment by jaymzmac** [comment]
Hi @carceneaux,

Thanks for your swift response. 

While I find some of your answers reassuring, I'm afraid I am not comfortable with the fact that the password for this user is stored in the organisation metadata.

Let me put it this way:
Would you consider this a secure design if VMware had developed vCD to store the passwords of all the organisation users this way? 

With regards to my suggestion:
`I would rather the plugin use the credentials of the user who is currently logged in to VMware Cloud Director.`

What I meant here was that I want SSO, but I would rather the plugin would use the credentials of the currently logged in user. So if I am logged in as 'admin@tentant' then this would be the user used to authenticate against Veeam. As I mentioned, this is how the VMware Cloud Director Availability plugin works, so it should be technically feasible. What do you think?

**Comment by carceneaux** [comment]
Thanks for the added information. 

`I'm afraid I am not comfortable with the fact that the password for this user is stored in the organisation metadata.`

The mitigating factor here is the only people with access to the metadata are already Organization Admins who already have access to the Veeam Self-Service Portal. Worst case scenario is an Org Admin is able to retrieve and decrypt the password but he's only getting access to what he is already privy to.

`What I meant here was that I want SSO, but I would rather the plugin would use the credentials of the currently logged in user. So if I am logged in as 'admin@tentant' then this would be the user used to authenticate against Veeam. As I mentioned, this is how the VMware Cloud Director Availability plugin works, so it should be technically feasible. What do you think?`

Authentication to the Veeam Self-Service Portal requires username & password. For this to work, these credentials would need to be stored somewhere (like metadata) so the plugin could then access them. It's not possible for a VCD plugin to retrieve the password of a user which is why I currently leverage the Service Account 'veeam.sa'.

**Comment by jaymzmac** [comment]
`The mitigating factor here is the only people with access to the metadata are already Organization Admins who already have access to the Veeam Self-Service Portal. Worst case scenario is an Org Admin is able to retrieve and decrypt the password but he's only getting access to what he is already privy to.`

I'm not sure that I agree with you that this is the worst case scenario. Is it not theoretically possible that someone with read only access to the database could obtain the metadata and from there easily decrypt the passwords and thus have admin access to all tenants? VMware support often ask for a copy of the database when troubleshooting issues. With the Veeam plugin enabled, they would effectively have org. admin access to all our tenants. 

Maybe we can trust VMware not to abuse this, but you see the point I'm trying to make? If someone manages to access the metadata (either through an exploit or otherwise), then it is trivial to obtain the cleartext password for the veeam.sa accounts.

I was able to do this with the following command in my environment:

`echo -n $metadata | openssl enc -d -base64 -A -aes-256-cbc -salt -k $orgID | jq .password -r | base64 -d`

Another issue that I can see is what if an org. admin leaves their role? This person could have made a note of the password for the veeam.sa account while they had access to the metadata. Nothing stops them from using this account after their own access has been removed. Should we introduce a policy to regenerate the veeam credentials every time a tenant makes a change to their permissions? I'm not so sure this is feasible.

`Authentication to the Veeam Self-Service Portal requires username & password. For this to work, these credentials would need to be stored somewhere (like metadata) so the plugin could then access them. It's not possible for a VCD plugin to retrieve the password of a user which is why I currently leverage the Service Account 'veeam.sa'.`

I understand it is not possible for the plugin to retrieve the password of a user. 

As I mentioned previously, we are using VMware Cloud Director Availability (VCDA) in our environment, and the plugin successfully authenticates to the VCDA Portal using the currently logged in user. 

Authentication from the plugin to the VCDA environment seems to occur using a VMware Cloud Director accessToken (jwt):
https://code.vmware.com/apis/1016/vmware-cloud-director-availability#/session/login

I guess this is not possible with VSSP since it requires a username & password? Perhaps my feature request then is for VSSP to allow authentication with a VCD access token?

**Comment by carceneaux** [comment]
I'll concede that another method of accessing the metadata is direct from the VCD database. Another method is all System Administrators have access to that data as well. Let's be honest, though, if your VCD database has been compromised you've got bigger issues to deal with.

You have a valid point for anytime someone who had access to the data leaves their employment. Companies tend to have a varying policy on this depending in the circumstances surrounding the employee leaving the company but it's always best practice to regenerate any credentials that person had access to. For example, in my previous employment for a Service Provider, customers would contact us ahead of time to disable/reset credentials when an employee was leaving their company.

Passwords can be regenerated as often as you like. Users already logged in to the VSSP will continue to work properly and new users will leverage the new credentials. Every time you complete the wizards for _SET VEEAM PORTAL_ or _REGENERATE CREDENTIALS_ in the plugin configuration screen, all tenant credentials are regenerated.

As previously mentioned, the only auth currently accepted for VSSP is username/password. JWT token is not a supported auth method. I completely understand what you're trying to do as I've put forward this Feature Request as well. I'll add your support to it. I have no ETA but I fully expect future updates to the VSSP to not require the username/password which will remove the Service Account requirement.

If my explanation for mitigating the risk is still insufficient, I recommend you use [v1.0 of the plugin](https://github.com/VeeamHub/veeam-plugin-for-vcd/releases/tag/v1.0) which does not leverage SSO.
